### ISSUE TITLE
GaussJordan - use of undefined ring elements!

### ISSUE THREAD

**Issue by malex984** [Singular/LELA#5]
lela/algorithms/gauss-jordan.tcc:74:    ctx.F.mulin (d, aii);   where d is undefined...!

started with EF.echelonize(D, true) for a Dense 10x10 (initialized!) matrix...

gdb backtrace:
#7  0x0000000000410b58 in CoeffDomain::mulin (this=0x7fffffffe3b0, x=..., y=...) at ../lela/ring/coeffs.h:606
#8  0x000000000042e736 in LELA::GaussJordan<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::GaussJordanTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > > > (this=0x7fffffffded8, A=..., k=0, d_0=..., U=..., P=..., r=@0x7fffffffc878, h=@0x7fffffffc86c, d=..., S=..., T=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:74
#9  0x000000000042ebdf in LELA::GaussJordan<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::GaussJordanTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > > > (this=0x7fffffffded8, A=..., k=0, d_0=..., U=..., P=..., r=@0x7fffffffd038, h=@0x7fffffffd02c, d=..., S=..., T=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:131
#10 0x000000000042ebdf in LELA::GaussJordan<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::GaussJordanTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > > > (this=0x7fffffffded8, A=..., k=0, d_0=..., U=..., P=..., r=@0x7fffffffd7f8, h=@0x7fffffffd7ec, d=..., S=..., T=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:131
#11 0x000000000042ebdf in LELA::GaussJordan<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::GaussJordanTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > > > (this=0x7fffffffded8, A=..., k=0, d_0=..., U=..., P=..., r=@0x7fffffffdd68, h=@0x7fffffffda2c, d=..., S=..., T=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:131
#12 0x0000000000425cab in LELA::GaussJordan<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::echelonize_reducedLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > > > (this=0x7fffffffded8, A=..., L=..., P=..., rank=@0x7fffffffdd68, det=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:453
#13 0x000000000041b85a in LELA::GaussJordan<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::echelonize_reducedLELA::DenseMatrix<Number, LELA::DenseMatrix<Number> > (this=0x7fffffffded8, A=..., L=..., P=...,

```
rank=@0x7fffffffdd68, det=...) at ../lela/algorithms/gauss-jordan.h:168
```
#14 0x00000000004172b3 in LELA::EchelonForm<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::echelonize (this=0x7fffffffdec0, A=..., reduced=true,

```
method=LELA::EchelonForm<MyModular<unsigned char>, LELA::AllModules<MyModular<unsigned char> > >::METHOD_ASYMPTOTICALLY_FAST_GJ) at ../lela/solutions/echelon-form.h:128
```

**Comment by hovinen** [comment]
Should be fixed now. Thanks.

**Comment by malex984** [comment]
still fails...

the problem is in: lela/algorithms/gauss-jordan.tcc:131

129         Element d_1;
130 
131         GaussJordanTransform (A_1, k, d_0, U, P, r_1, h_1, d_1, S, T, PS);

d_1 is undefined... 
:(

**Comment by hovinen** [comment]
Should be fixed now
